# Generated by Django 2.2.5 on 2019-09-21 14:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('bride_guest', models.BooleanField(default=False)),
                ('groom_guest', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPreferences',
            fields=[
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guest_preferences', serialize=False, to='guests.Guest')),
                ('special_diet', models.BooleanField(default=False)),
                ('invitation', models.BooleanField(default=False)),
                ('accommodation', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('second_day', models.BooleanField(default=False)),
            ],
        ),
    ]
