# Generated by Django 2.2.5 on 2019-09-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('priority', models.SmallIntegerField()),
                ('advert_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.AdvertCategories')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
