# Generated by Django 2.2.5 on 2019-09-21 14:41

import adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=adverts.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateTimeField(verbose_name='expiration_date')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=adverts.models.get_image_path)),
                ('premium', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='adverts.AdvertCategories')),
            ],
        ),
    ]
