# Generated by Django 2.2.5 on 2019-09-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdvertiserUser'),
        ),
        migrations.AddField(
            model_name='advert',
            name='scoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adverts.AdvertRating'),
        ),
    ]
